Add Plugin for BootsFaces in order to support <b:dataTable
apache/netbeans pull request #2357
Opened 2020-09-09 06:09 UTC by t-oster

Hi,

I am using NetBeans with BootsFaces (https://www.bootsfaces.net/). It works quite good, but the autocomplete fails on tags, which create scoped variables like `<b:dataTable value=[ListOfType<B>] var="x"/>` which creates a scoped variable `x` of type `B`.
I just copied the `@ServiceProvider(service = TagFeatureProvider.class)` from the PrimeFaces plugin, but since the org.netbeans.modules.web.jsfapi does not seem to expose this API I had to add my plugin as friend module.

I failed at creating a standalone module without adding a friend module, so my question is if you would include this module or what would be the correct way to add this functionality?

I also thought about a more generic plugin, where the user can specify a list of tags (namespace, tagName, var, value) which enables autocomplete in EL for those without creating a separate plugin for every taglib.

2020-09-11 18:35 UTC, lkishalmi requested changes

2020-09-11 18:35 UTC, lkishalmi commented on enterprise/web.bootsfaces/licenseinfo.xml
> +<licenseinfo>
Empty licenseinfo is not required.

2020-09-11 18:35 UTC, lkishalmi commented on enterprise/web.bootsfaces/src/org/netbeans/modules/web/bootsfaces/BootsFacesTagFeatureProvider.java
> +        DATA_TABLE(BOOTSFACES_UI_NAMESPACE, "dataTable", VALUE, VAR);
Trailing //NOI18N is missing

2020-09-11 18:35 UTC, lkishalmi commented on enterprise/web.bootsfaces/src/org/netbeans/modules/web/bootsfaces/BootsFacesTagFeatureProvider.java
> +    private static final String BOOTSFACES_UI_NAMESPACE = "http://bootsfaces.net/ui";
//NOI18N-s are missing

2020-09-11 19:25 UTC, t-oster commented on enterprise/web.bootsfaces/src/org/netbeans/modules/web/bootsfaces/resources/layer.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I tried to run without it, but it threw an Exception.

2020-09-11 19:28 UTC, t-oster commented
Thank you for the review, I will update it asap

2020-10-08 13:06 UTC, lkishalmi commented
Just remove the empty layer.xml I've checked out this PR removed the layer.xml, it still builds fine. Then we can finally merge this.

2020-10-08 13:15 UTC, t-oster commented
> Just remove the empty layer.xml I've checked out this PR removed the layer.xml, it still builds fine. Then we can finally merge this.

I will do this, but i think it will build fine, but it won't run when you try to install the plugin.

2020-10-13 17:23 UTC, lkishalmi approved these changes

2020-10-13 17:24 UTC, merged

2020-11-23 20:17 UTC, matthiasblaesing commented
This will not be part of 12.2 as the registration of the module in the cluster is missing: https://issues.apache.org/jira/browse/NETBEANS-5054

2020-11-23 21:22 UTC, t-oster commented
@matthiasblaesing is #2559 what I should do? I added it underneath web.primefaces, because that's what it is based on.