Setting the icon and categories for VSCode extension.
apache/netbeans pull request #2515
Opened 2020-11-02 12:49 UTC by dbalek

Before going to [Marketplace](https://marketplace.visualstudio.com/), the Apache NetBeans Language Server extension should provide an icon and search categories.
Updating the records in package.json.

2020-11-02 14:57 UTC, JaroslavTulach approved these changes
Extension with icon is nicer than without any icon. Thanks, Dušane!

2020-11-03 14:13 UTC, JaroslavTulach approved these changes

2020-11-03 15:19 UTC, lkishalmi requested changes
I'm just wondering how this one passed the license check of Travis...
Please update the licenseinfo.xml with the logo, just to be on the safe side.

2020-11-03 17:27 UTC, dbalek commented
> I'm just wondering how this one passed the license check of Travis...
> Please update the licenseinfo.xml with the logo, just to be on the safe side.

Done.

2020-11-04 11:35 UTC, JaroslavTulach approved these changes

2020-11-04 11:35 UTC, JaroslavTulach commented on java/java.lsp.server/vscode/package.json
> +				"label": "Java 8+",
The "Java 8+" name seems to nicely stress the core functionality of Apache NetBeans Language Server VSCode extension - e.g. the ability to run on JDK8 (other extensions require JDK11). I think it is a good name.

2020-11-04 15:05 UTC, lkishalmi approved these changes

2020-11-04 15:05 UTC, merged