Options panel use GTK default colors
apache/netbeans pull request #2744
Opened 2021-02-07 21:37 UTC by hectorespert

Use default colors in options panel when GTK laf is used.

2021-02-15 18:01 UTC, neilcsmith-net commented
Sorry, -1 from me on this.  Although +1 to fixing it.  We can't keep adding exceptions for look and feels over the code base.  Better to fix this so that a single key works for all LAFs.  If `separator.foreground` doesn't work for all, maybe a specific key for this panel that does?

2021-02-23 21:39 UTC, hectorespert commented
> Sorry, -1 from me on this. Although +1 to fixing it. We can't keep adding exceptions for look and feels over the code base. Better to fix this so that a single key works for all LAFs. If `separator.foreground` doesn't work for all, maybe a specific key for this panel that does?

I added a keys to modify this panel to allow remove LAFs exceptions but this PR only removes exceptions for the GTK laf.
I can't test other LAFs and they could be modified later.

2021-03-20 16:34 UTC, lkishalmi commented
A step in the good direction, though if we are adding new LAF keys, probably shall add constants for it in LFCustoms.
And by introducing that it would be good to check if all supported LAF-s are providing defaults for the new key.

A sidenote: It would be really great if you could detect somehow when the GTK skin is set to dark, if it does, it would be great at least add the ```"nb.dark.theme"``` to true.

2021-04-03 16:18 UTC, hectorespert commented
> A step in the good direction, though if we are adding new LAF keys, probably shall add constants for it in LFCustoms.

I added the new constants in LFCustoms.

> And by introducing that it would be good to check if all supported LAF-s are providing defaults for the new key.

New keys are only used by GTK theme, I would like to fix the problem with that theme before start to modify the other themes.

> A sidenote: It would be really great if you could detect somehow when the GTK skin is set to dark, if it does, it would be great at least add the `"nb.dark.theme"` to true.

A GTK configuration property to detect that is available: https://developer.gnome.org/gtk3/3.8/GtkSettings.html#GtkSettings--gtk-application-prefer-dark-theme

2021-04-16 10:09 UTC, geertjanw commented
Changing milestone to 12.5.

2021-07-21 12:28 UTC, ebarboni commented
@neilcsmith-net @lkishalmi  are the changes better now ? Can we consider merging ?

2021-07-21 12:52 UTC, lkishalmi requested changes
Generally I'm Ok with the implementation, just those constants...

2021-07-21 12:52 UTC, lkishalmi commented on platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/LFCustoms.java
> +    protected static final String OPTIONS_USE_UI_DEFAULT_COLORS = "Nb.options.useUIDefaultsColors";
Why protected instead of public?
"Nb" or "nb"? Yes I've seen both prefixes, however it would be good to stick with "nb.options"

2021-07-21 12:52 UTC, lkishalmi commented on platform/options.api/src/org/netbeans/modules/options/OptionsPanel.java
> +        CategoryButton button = UIManager.getBoolean("Nb.options.categories.button.useNimbusCategoryButton") //NOI18N
Would be nicer to reintroduce the same constants as in LFCustoms at the top of the file again (now it can be not public)

2021-07-23 09:18 UTC, ebarboni commented
change resquested moving to 12.6 for now

2021-12-17 21:48 UTC, matthiasblaesing commented
This seems to be a working implementation, which even looks like a cleanup. Any reason not to merge now? (the unittests that fail are known to be flaky).

2021-12-18 11:14 UTC, hectorespert commented
> Any reason not to merge now?

It's only waiting for a positive review.

2021-12-18 15:50 UTC, lkishalmi approved these changes
Seems to be fine now.

2021-12-18 15:51 UTC, merged