Micronaut project creation fix
apache/netbeans pull request #3506
Opened 2022-01-25 21:06 UTC by matthiasblaesing

Micronaut projects are generated by the https://micronaut.io/launch/ service, which creates a ZIP file with the project contents.

The NetBeans integration unzips that file and invokes the gradle/maven build. Micronaut uses either the maven or gradle wrappers and on unixoid systems this wrapper needs to be executable. This is fixed in 9de1d4b.

In addition the user is informed, that he should be careful to trust the system used to generate the project file:

![Bildschirmfoto-20220125211631-911x565](https://user-images.githubusercontent.com/2179736/151059631-4050c668-518a-432c-b285-b1f63b23ddc4.png)

2022-01-26 07:26 UTC, mbien approved these changes
LGTM - the added warning is great too

2022-01-26 09:40 UTC, neilcsmith-net requested changes
Thanks for getting ahead of me on this one.

Minor typo to fix.

The UI code is possibly more complicated than it needs to be.  Can you not use the NotificationLineSupport::setWarningMessage for this?

Still not particularly keen on download and execute as single action, but can live with it with the warning.  Pinging @vieiro for review too.

This has missed the boat for 13-rc2 anyway, so doesn't need merging until early next week.

2022-01-26 09:42 UTC, neilcsmith-net requested changes

2022-01-26 09:42 UTC, neilcsmith-net commented on enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/Bundle.properties
> +BasePropertiesVisual.jLabel1.text=<html>Only finish this dialog if you trust the choosen service. Code from that service is downloaded and executed on this machine.
Minor typo : ~~choosen~~ service ? chosen service.

2022-01-26 12:55 UTC, vieiro approved these changes

2022-01-26 12:57 UTC, vieiro commented
Hi @neilcsmith-net . I can't really review this one, but a quick look reasonable.

Two questions:
- A) Are we setting the background color in that notice? It seems to me is reducing contrast. Can't tell how this looks in a dark mode.
- B) Is this expected to solve NETBEANS-6401 ? If so I'm missing setting an executable bit in "mvnw" after unzipping, right?

Thanks,
Antonio

2022-01-26 13:05 UTC, neilcsmith-net commented
Thanks @vieiro Wanted your review primarily on principle and text.

Execute bit is set at https://github.com/apache/netbeans/blob/9de1d4bafd8d602b646b4bc8595b7fb3fb3fb33a/enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/MicronautProjectWizardIterator.java#L237

Have similar concern on UI, hence wondering if NotificationLineSupport would work better and simplify the changes.

2022-01-26 13:08 UTC, vieiro commented
> Thanks @vieiro Wanted your review primarily on principle and text.
> 
> Execute bit is set at
> 
> https://github.com/apache/netbeans/blob/9de1d4bafd8d602b646b4bc8595b7fb3fb3fb33a/enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/MicronautProjectWizardIterator.java#L237
> 
> Have similar concern on UI, hence wondering if NotificationLineSupport would work better and simplify the changes.

Yep, I've seen the executable bit later. +1 to the NotificationLineSupport if possible.

2022-01-26 13:19 UTC, matthiasblaesing commented
Will have a look at NotificationLineSupport, but I had tested the display with different LAFs and I remember definitely testing DarkNimbus. My eyes were still ok afterwards, but maybe its even easier/looks better with NotificationLineSupport.

2022-01-26 13:50 UTC, neilcsmith-net commented
@matthiasblaesing actually, it might conflict with other messages being set by the wizard here - eg. the error messages in `valid(..)`.  Any immediate concern with that, then let's just fix the typo and keep as is.

2022-01-26 20:17 UTC, matthiasblaesing commented
I finally remembered, that I ran hard against `NotificationLineSupport`: It is good for very short texts and utterly fails for anyhing longer than a handful of words. This is also the case here (hint: the sentence does not end where it is cut here):

![truncated_text](https://user-images.githubusercontent.com/2179736/151239706-2db1bec2-0dac-4588-a6b0-3c675b30b6d9.png)

Here are screenshots in the various LAFs:

Metal:
![base_metal](https://user-images.githubusercontent.com/2179736/151239884-44521be7-62b2-44e2-a251-879b987effab.png)

Nimbus:
![base_nimbus](https://user-images.githubusercontent.com/2179736/151239912-3d550b6f-b631-4dd6-b92c-c495dfab3946.png)

CDE/Motif:
![base_cde_motif](https://user-images.githubusercontent.com/2179736/151239937-34d93ddc-b607-4720-80ce-07963876ff54.png)

GTK:
![base_gtk](https://user-images.githubusercontent.com/2179736/151239956-bf9a0429-86d6-411f-a3c9-c4036c10fe0c.png)

Flatlaf:
![base_flatlaf_light](https://user-images.githubusercontent.com/2179736/151239990-1225e275-aa35-4f0b-be4b-c98b3dc142a0.png)

Flatflaf (Dark):
![base_flatlaf_dark](https://user-images.githubusercontent.com/2179736/151240026-735b4b4b-ddb5-484c-b91e-bc39169a2f4f.png)

Metal (Dark):
![base_metal_dark](https://user-images.githubusercontent.com/2179736/151240055-16486ef2-266a-4ab8-9ea2-3240d94b448c.png)

Nimbus (Dark):
![base_nimbus_dark](https://user-images.githubusercontent.com/2179736/151240091-2965127b-8112-4df0-91c9-7123f6a96608.png)

2022-01-27 08:21 UTC, mbien commented
I think it looks really nice + this PR fixes an important issue. I suppose it could be make more DRY by updating the notification service and letting it use it like Neil suggested but I feel this would have low priority when taken in context. Updating the notification support would also require more testing since its used everywhere. Still +1 from me.

2022-01-27 10:24 UTC, neilcsmith-net commented
Thanks @matthiasblaesing and kudos for all the screenshots - above and beyond! :smile: Tested locally too.  Will merge.

> I ran hard against NotificationLineSupport: It is good for very short texts and utterly fails for anyhing longer than a handful of words.

Yes, you need to add `<br>` tags. I may look at a wrapping fix some time, but not for this!

@mbien it wasn't from a DRY perspective, at least not code anyway! Icons and colours spread across the code base tend to cause problems over time.  But this solves the immediate concerns so I'm merging.

2022-01-27 10:25 UTC, neilcsmith-net approved these changes
@matthiasblaesing do you want to squash and merge?  Or I can.  But please do to the PR and merge that so we don't lose the link.  Thanks.

2022-01-27 11:31 UTC, mbien commented
> @mbien it wasn't from a DRY perspective, at least not code anyway! Icons and colours spread across the code base tend to cause problems over time.

sure DRY is goes beyond code.

2022-01-27 13:28 UTC, neilcsmith-net commented
@mbien you're reading that the opposite way to how it was intended. Code-wise it wasn't (mostly) about DRY. Anyway, this change is good to go  - any follow up discussion can happen elsewhere if need be.

2022-01-27 16:54 UTC, matthiasblaesing commented
@neilcsmith-net squashed the commits I wanted squashed and adjusted the title of the second commit to refer to the JIRA issue. Feel free to merge when this gets green.

2022-01-27 17:55 UTC, neilcsmith-net commented
@matthiasblaesing thanks, yes, that split into two commits makes sense.  If you see it green before me, feel free to merge too.

2022-01-27 20:37 UTC, merged