#4923: access to gradle internal APIs is protected from failing the project load, just logs a notification.
apache/netbeans pull request #4936
Opened 2022-11-07 17:35 UTC by sdedic

The culprit for the reported error (see #4923) is a `LinkageError` as the gradle version configured for the build changed its internal APIs (a change needed to adopt Groovy 4.0). It's true that now the gradle project loader accesses even gradle internal APIs that can be less stable than the proper APIs.

This PR centralizes the gradle internal access to `GradleInternalAdapter` class. Each call to an internal API should be now guarded with `safeCall` that blocks thrown `Errors` and `RuntimeExceptions` and logs them as problems, but continue the loading process.

The main `NbProjectInfoBuilder` should be now free of references to Gradle internals. To accommodate different API versions, the Adapter can be subclassed with alternative implementations for both newer or older versions that the one the gradle tooling is compiled againts.

2022-11-07 21:49 UTC, mbien approved these changes
I like this implementation.

2022-11-08 05:47 UTC, lkishalmi commented
Well, better than none, though I feel we have cut ourselves by using Gradle internal stuff. I fear this is just a bandaid.

2022-11-08 05:58 UTC, lkishalmi requested changes
I've created a branch for Gradle 7.6-rc-1 upgrade. This one cannot compile with Gradle 7.6 as of:

```
build-tooling-lib:
> Task :clean

> Task :compileJava FAILED
/home/lkishalmi/NetBeansProjects/netbeans/extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/GradleInternalAdapter.java:95: error: cannot find symbol
        return etv.isFixedValue();
                  ^
  symbol:   method isFixedValue()
  location: variable etv of type ExecutionTimeValue
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

2022-11-08 07:16 UTC, sdedic commented
> I've created a branch for Gradle 7.6-rc-1 upgrade. This one cannot compile with Gradle 7.6 as of:
> 
The same reason as `hasFixedValue` could not compile on pre-7.6-rc-1. The PR uses regular call for the bundled gradle, and reflection for 'the other versions'. I thought the code will change to  compile against 7.6 when the bundled APIs are upgraded (and will use reflection to work with earlier versions).

2022-11-08 08:08 UTC, sdedic commented
@lkishalmi if you point me to the branch for 7.6 update, I can contribute apdated reflection code there.

2022-11-08 09:30 UTC, sdedic commented
@neilcsmith-net please decide on the solution with respect to the release schedule:

1.  leave unattended for NB16
2. go with the PR as it is, then upgrade to Gradle 7.6-rc1 to cover JDK19 
3. make calls for both versions reflective for NB16, then discuss whether that is appropriate
4. other solution

2022-11-08 09:47 UTC, neilcsmith-net commented
@sdedic I'd rather stay out of making that call if possible.  That's one for you and other reviewers to make primarily - this is covered at https://lists.apache.org/thread/hyjbsz55zb9xfcnccghkrsvqsnt83nwf

Maybe @MartinBalin has a view from releases side?  If this was in Maven support I'd feel more comfortable taking a view.  @ebarboni ?

2022-11-08 10:09 UTC, sdedic commented
> @sdedic I'd rather stay out of making that call if possible. 

OK, let's wait (even with RC4 ?) on how the consensus evolves.

2022-11-08 10:56 UTC, MartinBalin commented
I would like to proceed and merge this PR for RC4 NB16 don't wait for next release.

2022-11-08 11:04 UTC, neilcsmith-net commented
OK, @MartinBalin made the call - we're having RC4! :smile:

Let's hold off merge until @lkishalmi is happy with what's going in.

2022-11-08 16:52 UTC, lkishalmi approved these changes
Well, re-checked the implementation. Changing my vote.
I'm more on favor to have this one on NB16, then probably have the Gradle upgrade on NB17.

2022-11-08 18:47 UTC, merged

2022-11-08 19:54 UTC, swpalmer commented
Gradle 7.6-RC-2 has become available, so it will be at least another week before a Gradle 7.6 release is possible.  Makes sense not to hold up NB 16 when we have this PR to cover the gap until NB 17 can include the updated Gradle.ScottOn Nov 8, 2022, at 11:52 AM, Laszlo Kishalmi ***@***.***> wrote:﻿
@lkishalmi approved this pull request.

Well, re-checked the implementation. Changing my vote.
I'm more on favor to have this one on NB16, then probably have the Gradle upgrade on NB17.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>