Typo correction
apache/netbeans pull request #5583
Opened 2023-03-01 10:15 UTC by AanshSavla

Fixed typos
Descritpion -> Description
Descritption -> Description
Moudle -> Module

---
**^Add meaningful description above**

By opening a pull request you confirm that, unless explicitly stated otherwise, the changes -

 - are all your own work, and you have the right to contribute them.
 - are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for more information).

Please make sure (eg. `git log`) that all commits have a valid name and email address for you in the Author field.

If you're a first time contributor, see the Contributing guidelines for more information.

If you're a committer, please label the PR before pressing "Create pull request" so that the right test jobs can run.

2023-03-01 14:04 UTC, mbien commented on java/java.navigation/src/org/netbeans/modules/java/navigation/ElementNode.java
> +    public Description getDescription() {
note to self: checked and `java.navigation` does not export this package (or any other package). `Description` itself is package private interestingly.

@matthiasblaesing can we make this method package private?

2023-03-01 14:09 UTC, mbien commented on java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/elements/ElementNode.java
> +    public Description getDescription() {
note to self: similar here, package is not exported. However the difference is that `Description` is public.

2023-03-01 14:12 UTC, mbien commented on platform/o.n.core/src/org/netbeans/core/ui/SwingBrowser.java
> +    public String getDescription () {
note to self: we are lucky here too, package not exported.

2023-03-01 14:17 UTC, mbien requested changes
commits here still contain an invalid email, you can see it here:
https://patch-diff.githubusercontent.com/raw/apache/netbeans/pull/5583.patch

would need fixing before this can be integrated

2023-03-01 14:19 UTC, AanshSavla commented
> commits here still contain an invalid email, you can see it here: https://patch-diff.githubusercontent.com/raw/apache/netbeans/pull/5583.patch
> 
> would need fixing before this can be integrated

@mbien Can you suggest where can I make these changes?

2023-03-01 14:43 UTC, mbien commented
@AanshSavla I already did on the first PR you created https://github.com/apache/netbeans/pull/5577#pullrequestreview-1318033729

2023-03-01 14:45 UTC, AanshSavla commented
> @AanshSavla I already did on the first PR you created [#5577 (review)](https://github.com/apache/netbeans/pull/5577#pullrequestreview-1318033729)

The problem was in my git config. I just changed it in local repo. But figuring out that how to push it on remote repo.

2023-03-02 02:07 UTC, mbien approved these changes
I squashed the commits for you. Going to merge in a day or two assuming the tests are green.

2023-03-02 11:19 UTC, tbw777 commented
@AanshSavla 
shoudl 18 matches

2023-03-02 16:56 UTC, mbien commented
merging. @AanshSavla congrats to your first contribution!

2023-03-02 16:56 UTC, merged

2023-03-02 17:31 UTC, AanshSavla commented
Thank You! @mbien