FlatLaf: change accent color in Options dialog (Appearance > FlatLaf)
apache/netbeans pull request #5795
Opened 2023-04-08 00:23 UTC by DevCharly

Since changing accent color in FlatLaf custom properties does not work as expected for Cupertino themes (see issue #5461),
I've added a combobox to the options dialog to allow setting accent color in UI. FlatLaf API is used to enable accent color so that it works correctly in Cupertino themes.

![grafik](https://user-images.githubusercontent.com/5604048/230694039-58bcd628-d42a-451a-b72f-2017d8e6939c.png)

There are some predefined accent colors, which work good for light and dark themes. These are the same colors that macOS (and FlatLaf Demo app) uses. There is also a "Custom" item in the combobox that allows to set any color.

![grafik](https://user-images.githubusercontent.com/5604048/230692669-ee92a742-d493-470a-ab04-4f594c6087c2.png)

The colors are defined in `FlatLaf.properties` (key `nb.accentColors.predefined`).

2023-04-08 09:47 UTC, DevCharly commented
BTW we can of course use other predefined accent colors. Maybe some from the Windows 11 accent colors. Suggestions are welcome.

![grafik](https://user-images.githubusercontent.com/5604048/230713965-945511af-411a-4b45-a6bd-15b80b7c1625.png)

To try various accent colors I recommend using [FlatLaf Theme Editor](https://www.formdev.com/flatlaf/theme-editor/) because it has **live preview** and a **color picker**:  To do so, create/open an empty directory in theme editor, create two properties files, one for light and one for dark, and add following:

~~~
@accentColor = #FF453A
~~~

Theme Editor preview now looks like this:

![grafik](https://user-images.githubusercontent.com/5604048/230714435-f8d9894f-5279-4db3-8e7d-8e13a81af92f.png)

Select "Focused" checkbox to show all preview components in focused state.

2023-04-08 13:12 UTC, neilcsmith-net approved these changes
I wanted to do a UI for exactly this after doing the initial properties file support.  Generally in favour.

Isn't the fact that the accent color in the properties files is ignored in the Cupertino themes a bug in FlatLaf?

Ideally we'd find a way to store the setting in the properties file, rather than Preferences.  I initially wanted to find a way to have 2-way editing (UI and text) for that.  And load/save support (eg. share NetBeans themes).  The file is deliberately read from the system config filesystem too, eg. so that platform developers can provide an alternative non-empty implementation via the layer.

2023-04-09 21:55 UTC, eirikbakke requested changes
Nice! How does this setting interact with other ways of manipulating FlatLAF properties, such as the "Edit custom properties" button, or changing platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties/FlatDarkLaf.properties? If the color is left at "default", is the behavior the same as before?

Code formatting: Tabs in the patch should be replaced by four spaces as in the rest of the file.

(In the future it would be cool if the entire FlatLAF Theme Editor could just be exposed from a button in the Options dialog.)

2023-04-09 21:55 UTC, eirikbakke commented on platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafOptionsPanel.java
> +		initAccentColor();
Some indent problems in this patch/file (mix of tabs and spaces). Existing indents are spaces, so maybe use spaces.

2023-04-09 21:55 UTC, eirikbakke commented on platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafOptionsPanel.java
> +                if (sepIndex > 1) {
Technically should be >= 1, but there are no single-character color names, so it doesn't really matter...

2023-04-09 21:55 UTC, eirikbakke commented on platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafPrefs.java
> +        return parseColor(prefs.get(ACCENT_COLOR, null));
What happens in this case when the "default" color was selected? Does the accent color then end up being taken from the various FlatLAF.properties files, or does it end up being explicitly set to the zero-alpha DEFAULT color, with invisible accents?

2023-04-11 21:26 UTC, DevCharly commented
> How does this setting interact with other ways of manipulating FlatLAF properties, such as the "Edit custom properties" button, or changing platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties/FlatDarkLaf.properties?

The accent color is stored in NB preferences store and overrides `@accentColor`.
Function `systemColor(accent)` is used in properties files to get this color into FlatLaf UI defaults.
See PR https://github.com/JFormDesigner/FlatLaf/pull/607

> If the color is left at "default", is the behavior the same as before?

Yes.

2023-04-11 22:55 UTC, eirikbakke commented on platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/Installer.java
> +		} );
Some more tabs instead of spaces here...

2023-04-11 22:56 UTC, eirikbakke commented on platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafPrefs.java
> +	}
Some more tabs instead of spaces here...

2023-04-11 23:49 UTC, eirikbakke approved these changes
I tried the latest version of the patch and it works, including the following cases:
* Selecting the default accent color after previously having one of the other presets selected
* Overriding with the "Edit custom properties" button. If the accent color is set here, it overrides the setting from the combo box, which makes sense given the label over the button. Removing the accent color from the properties file makes the combo box choice work again.
* Custom accent color from color chooser works.

One small hiccup:
* Picking a different accent color and switching to Cupertino Light works except: The user now gets _two_ "Restart IDE" notifications, and if they restart from the one that was triggered by the accent color change, they won't have the chance to get the effect of "Switch to matching editor colors profile."

Not sure it's worth doing something about the latter case, though, unless it's trivial to fix...

2023-04-12 00:11 UTC, DevCharly commented
> The user now gets two "Restart IDE" notifications, ...

I think it is difficult to avoid the two notifications because they are implemented in different modules.

However I've changed the priority of the "accent color" notification from HIGH to NORMAL.
There are still two notifications, but now always the "look and feel" notification is show at the status bar.

2023-04-12 00:28 UTC, eirikbakke commented
@DevCharly Great, that probably improves usability for this corner case. Thanks!

2023-04-12 11:35 UTC, DevCharly commented
> Isn't the fact that the accent color in the properties files is ignored in the Cupertino themes a bug in FlatLaf?

The `@accentColor` variable is indeed not used for all accent colors in Cupertino/macOS themes.

But wouldn't say it is a bug. It's more a design decision to use `systemColor(accent)` (see PR https://github.com/JFormDesigner/FlatLaf/pull/607) as common way to get accent color (e.g. from operating system or from app preferences).

But I must confess that I have not considered the NetBeans use case... 
Probably will rework Cupertino themes...

2023-04-12 20:59 UTC, mbien approved these changes
played with it a bit and it worked great. (code looks good too)

please merge when ready to reduce PR backlog before freeze.

2023-04-14 20:11 UTC, merged