Dbalek/micronaut class generator fixes
apache/netbeans pull request #6107
Opened 2023-06-21 12:16 UTC by dbalek

Fixing generator of Micronaut entity classes and repositories for the case that entities need PK classes to be generated.

2023-06-23 15:26 UTC, MartinBalin approved these changes

2023-06-26 10:27 UTC, jhorvath requested changes

2023-06-27 07:38 UTC, dbalek commented on enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautEntity.java
> +                    if (isPKMember && needsPKClass && jakartaSupported) {
Done.

2023-06-27 09:20 UTC, jhorvath approved these changes
Looks good

2023-06-28 06:35 UTC, merged