GCN-4643: Check for source level java compatibility
apache/netbeans pull request #7555
Opened 2024-07-08 16:00 UTC by petrovic-d

This feature checks if source level java (from the project) is compatible with one used by extension
It ignores check when RH extension is installed
It also works with multi-module projects

2024-07-09 09:29 UTC, sdedic requested changes

2024-07-09 09:29 UTC, sdedic commented on java/java.lsp.server/vscode/src/jdk/validation/project.ts
> +const GRADLE_TARGET_COMPATIBILITY_REGEX = /targetCompatibility\s*=\s*(?:JavaVersion\.toVersion\(['"](\d+(\.\d+)?)['"]\)|['"](\d+(\.\d+)?)['"])/
Nitpick: sadly the `JavaVersion.toVersion("string")` is a groovy script code, so there can be `\s*` between identifiers, literals and symbols. Unlikely to happen, though.

2024-07-09 09:29 UTC, sdedic commented on java/java.lsp.server/vscode/src/jdk/validation/project.ts
> +    protected abstract extractJavaVersion(): number | undefined
Please file an issue against Netbeans project, to extend `GET_PROJECT_INFO` (or provide an additional command) with java settings -- the source/target/release info is already internally available from maven/gradle parsing itself; just not exported to LS protocol.

Note the issue # here and note this code location in that issue as well, so it is eventually updated when the info becomes available.

2024-07-09 09:29 UTC, sdedic commented on java/java.lsp.server/vscode/src/jdk/validation/project.ts
> +    const projectInfos: any[] = await vscode.commands.executeCommand(GET_PROJECT_INFO, projectUri.toString(), { projectStructure: true });
If searching for maximum required java, add `recursive: true` to also cover grand-child subprojects.

2024-07-09 09:29 UTC, sdedic commented on java/java.lsp.server/vscode/src/jdk/validation/project.ts
> +        this.directory = directory.replace('file:/', '');
Note: this may produce `C:/Temp/whatever` paths on Windows. Possibly transform e.g. using `vscode.Uri.parse(directory).fsPath`

2024-07-09 09:29 UTC, sdedic commented on java/java.lsp.server/vscode/src/extension.ts
> +    validateJDKCompatibility(currentJdk);
note -- there's a pending PR #7497 that introduces `projectJDK`. Depending on which one will merge first, the other PR should change to validate the `projectJDK`

2024-07-09 09:29 UTC, sdedic commented on java/java.lsp.server/vscode/src/jdk/validation/project.ts
> +            const subInfos: any[] = await vscode.commands.executeCommand(GET_PROJECT_INFO, `file:/${subproject.directory}`);
Use `vscode.Uri.file(path).toString()`

2024-07-09 12:23 UTC, dbalek commented
Do not forget to squash all the commits into a single one before merge.

2024-07-09 16:12 UTC, junichi11 commented
Please add the license header.

2024-07-09 19:07 UTC, sdedic commented on java/java.lsp.server/vscode/src/jdk/validation/extensionUtils.ts
> +    if (!commands.includes(command)) {
We no longer need the check for a particular command .... the client will either start and the promise fullfills, or the client fails, the promise fais - which causes `await nblsClient` to throw an error on itself. If the client initializes, but fails to register the command for whatever reason, vscode's `commands.executeCommand()` will throw an error.  So no other explicit throw is necessary, IMHO.

2024-07-10 06:59 UTC, sdedic approved these changes

2024-07-10 08:07 UTC, dbalek approved these changes

2024-07-10 13:45 UTC, mbien commented
was about to say that something went wrong during squashing, but this looks better now :)

2024-07-10 20:57 UTC, merged