Cloud Assets - build and push docker command
apache/netbeans pull request #7642
Opened 2024-08-06 13:01 UTC by jhorvath

Added a command to build and push the Docker image to a selected repository. I cleaned up the dependencies of maven.indexer. Note that javax.inject is now in a separate module within the platform cluster.

2024-08-09 09:06 UTC, sdedic requested changes

2024-08-09 09:06 UTC, sdedic commented on enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/ImageBuilderCommand.java
> +                                    goals = List.of("compile", "deploy", "-pl", "oci", "-Dpackaging=docker", "-Djib.to.image=" + repository.getUrl()+ ":" + version);
I think this if-else can be replaced by `RunConfig.setReactorStyle(ALSO_MAKE)` that generates `--projects <list> --also-make` into the commandline.

2024-08-09 09:06 UTC, sdedic commented on enterprise/websvc.restlib/nbproject/project.xml
> +                <!--<package>javax.inject</package>-->
Leftover comment ?

2024-08-09 09:06 UTC, sdedic commented on java/maven.embedder/nbproject/project.xml
> +<!--            <class-path-extension>
leftover comment

2024-08-09 09:06 UTC, sdedic commented on platform/libs.javax.inject/external/jakarta.inject-2.6.1-license.txt
> +Origin: https://github.com/eclipse-ee4j/glassfish-hk2
The name and origin seem incorrect

2024-08-09 09:06 UTC, sdedic commented on platform/libs.javax.inject/src/org/netbeans/libs/javax/Dummy.java
> +package org.netbeans.libs.jsr223;
bad package !

2024-08-15 08:07 UTC, jhorvath commented on enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/ImageBuilderCommand.java
> +                            task.waitFinished();
Temporary file is deleted in the TaskListener now

2024-08-15 08:10 UTC, jhorvath commented on enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/ImageBuilderCommand.java
> +                                task.waitFinished();
Using `TaskListener` now

2024-08-15 13:53 UTC, sdedic approved these changes
Seems OK. 
As this adds a new module, I'll re-run the tests with `ci:all` so everything is built / tested

2024-08-15 13:53 UTC, sdedic commented on enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/ImageBuilderCommand.java
> +        NotifyDescriptor.InputLine desc = new NotifyDescriptor.InputLine("Enter image tag", "Enter an image tag");
Nitpick: I18N

2024-08-16 06:02 UTC, merged